export default {
  channels: [
    { name: 'gdn', category: 'google', type: 'network',  },
    { name: 'google-ads', category: 'google', type: 'network',  },
    { name: 'google-search', category: 'google', type: 'search',  },
    { name: 'google-discovery', category: 'google', type: 'content',  },
    { name: 'youtube', category: 'google', type: 'sns',  },
    { name: 'facebook', category: 'facebook', type: 'sns',  },
    { name: 'instagram', category: 'facebook', type: 'sns',  },
    { name: 'mediamath', category: 'mediamath', type: 'network',  },
    { name: 'ttd', category: 'ttd', type: 'network',  },
    { name: 'criteo', category: 'criteo', type: 'network',  },
    { name: 'appier', category: 'appier', type: 'network',  },
    
    { name: 'naver-search', category: 'naver', type: 'search', },
    { name: 'naver-nosp', category: 'naver', type: 'content', },
    { name: 'naver-gfa', category: 'naver', type: 'content' },
    { name: 'daum-search', category: 'kakao', type: 'search', },
    { name: 'daum-display', category: 'kakao', type: 'content' },
    { name: 'kakao-bizboard', category: 'kakao', type: 'content'},
    { name: 'kakao-friends', category: 'kakao', type: 'sns', },
    { name: 'widerplanet', category: 'widerplanet', type: 'network',  },
    { name: 'tnk', category: 'tnk', type: 'cpa' },
    { name: 'tenping', category: 'tenping', type: 'cpa' },
  ].map((d,i)=>Object.assign({id: i+1}, d)),
  campaigns: [
    { title: '8K Playground', 
      name: 'playground8k',
      landings: ['https://www.samsung.com/sec/8k/playground/'],
      tags: ['t1', 'Lois'],  },
    { title: '비스포크 웨딩샵', 
      tags: ['t3', 'Peach'], 
      landings: ['https://www.samsung.com/sec/eventList/bespoke'], },
    { title: 'TV 보상판매', 
      tags: ['t1', 'Erin'], 
      landings: ['https://www.samsung.com/sec/eventList/tv_tradein'], },
    { title: '갤럭시20', 
      tags: ['t1', 'Jade'], 
      landings: ['https://www.samsung.com/sec/event/galaxy20-launch', 'https://www.samsung.com/sec/event/galaxy20-preview'] },
    { title: '갤럭시 노트10', 
      tags: ['t3', 'Baro'] },
    { title: '갤럭시 버즈플러스', 
      tags: ['t1', 'Rachel'] },
    { title: '제트청소기', 
      tags: ['t3', 'Lucy'] },
    { title: '그랑데AI', 
      tags: ['t2', 'Jeremy'] },
    { title: '인덕션2020', 
      tags: ['t2', 'Bella'] },
    { title: '무풍으시시', 
      tags: ['t2', 'Kathy'] },
  ]
}